# Generated by Django 2.2.5 on 2019-09-21 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=6)),
                ('is_1_selected', models.SmallIntegerField()),
                ('is_2_selected', models.SmallIntegerField()),
                ('is_3_selected', models.SmallIntegerField()),
                ('is_4_selected', models.SmallIntegerField()),
                ('is_5_selected', models.SmallIntegerField()),
                ('is_6_selected', models.SmallIntegerField()),
                ('is_7_selected', models.SmallIntegerField()),
                ('is_8_selected', models.SmallIntegerField()),
                ('is_9_selected', models.SmallIntegerField()),
                ('is_10_selected', models.SmallIntegerField()),
                ('is_11_selected', models.SmallIntegerField()),
                ('is_12_selected', models.SmallIntegerField()),
                ('is_13_selected', models.SmallIntegerField()),
                ('is_14_selected', models.SmallIntegerField()),
                ('is_15_selected', models.SmallIntegerField()),
                ('is_16_selected', models.SmallIntegerField()),
                ('is_17_selected', models.SmallIntegerField()),
                ('is_18_selected', models.SmallIntegerField()),
                ('is_19_selected', models.SmallIntegerField()),
                ('is_20_selected', models.SmallIntegerField()),
                ('is_21_selected', models.SmallIntegerField()),
                ('is_22_selected', models.SmallIntegerField()),
                ('is_23_selected', models.SmallIntegerField()),
                ('is_24_selected', models.SmallIntegerField()),
                ('is_25_selected', models.SmallIntegerField()),
                ('is_26_selected', models.SmallIntegerField()),
                ('is_27_selected', models.SmallIntegerField()),
                ('is_28_selected', models.SmallIntegerField()),
                ('is_29_selected', models.SmallIntegerField()),
                ('is_30_selected', models.SmallIntegerField()),
                ('is_31_selected', models.SmallIntegerField()),
                ('is_32_selected', models.SmallIntegerField()),
                ('is_33_selected', models.SmallIntegerField()),
                ('is_34_selected', models.SmallIntegerField()),
                ('is_35_selected', models.SmallIntegerField()),
                ('is_36_selected', models.SmallIntegerField()),
                ('is_37_selected', models.SmallIntegerField()),
                ('is_38_selected', models.SmallIntegerField()),
                ('is_39_selected', models.SmallIntegerField()),
                ('is_40_selected', models.SmallIntegerField()),
                ('is_41_selected', models.SmallIntegerField()),
                ('is_42_selected', models.SmallIntegerField()),
                ('is_43_selected', models.SmallIntegerField()),
                ('is_44_selected', models.SmallIntegerField()),
                ('is_45_selected', models.SmallIntegerField()),
                ('is_46_selected', models.SmallIntegerField()),
                ('is_47_selected', models.SmallIntegerField()),
                ('is_48_selected', models.SmallIntegerField()),
                ('is_49_selected', models.SmallIntegerField()),
            ],
        ),
    ]
